-- ============================================================
-- GEO Composer: geo_directives table
-- Reference: ROADMAP.md P7.2.1, ARCHITECTURE.md §11.3
-- ============================================================

CREATE TABLE IF NOT EXISTS geo_directives (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id                   UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  version                     INT  NOT NULL DEFAULT 1,
  -- 'draft' | 'active' | 'archived'
  status                      TEXT NOT NULL DEFAULT 'draft'
                                CHECK (status IN ('draft', 'active', 'archived')),

  -- Core directive content (generated by GEO Composer)
  primary_recommendation      TEXT NOT NULL DEFAULT '',
  scenarios                   JSONB NOT NULL DEFAULT '[]',
  audience_signals            JSONB NOT NULL DEFAULT '{}',
  competitive_positioning     TEXT NOT NULL DEFAULT '',

  -- Source references (what generated this directive)
  source_brief_id             UUID REFERENCES master_briefs(id) ON DELETE SET NULL,
  source_tracker_snapshot_id  UUID REFERENCES ai_visibility_snapshots(id) ON DELETE SET NULL,

  -- Deployment tracking: URLs where this directive has been installed
  deployed_pages              TEXT[] NOT NULL DEFAULT '{}',

  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Only one active directive per client at a time
CREATE UNIQUE INDEX IF NOT EXISTS idx_geo_directives_active
  ON geo_directives(client_id) WHERE status = 'active';

-- Fast lookup: all directives for a client, newest first
CREATE INDEX IF NOT EXISTS idx_geo_directives_client_created
  ON geo_directives(client_id, created_at DESC);

-- Auto-update updated_at on any row change
CREATE OR REPLACE TRIGGER geo_directives_updated_at
  BEFORE UPDATE ON geo_directives
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- RLS: service role only (internal admin tool, no user-facing auth yet)
ALTER TABLE geo_directives ENABLE ROW LEVEL SECURITY;

CREATE POLICY "service_role_all" ON geo_directives
  FOR ALL TO service_role USING (true) WITH CHECK (true);
